sinan_vigilancia:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: sinan_vigilancia
      schema: dev
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 2